baseURL = 'https://leunam.dev'
languageCode = 'en-us'
title = 'Baitinq'
enableRobotsTXT = true
enableGitInfo = true
disablePathToLower = true

theme = "researcher"

[params]
  author = "Baitinq"
  description = "Personal website."
  favicon = "favicon.ico"  # path to a .ico to use as favicon
  logo = ""  # url or path to a logo to put in the header
  [params.footer1]
    text = "By Baitinq"
    url = "https://github.com/Baitinq/baitinq.ml"
  [params.footer2]
    text = "Hosted on NixOS."
    url = "https://nixos.org"
  [params.style]  # appearance options (can be omitted)
    fontFamily = "Inconsolata"
    pageWidth = "750px"
    avatarSize = "90px"
    colorBlack = "#222222"
    colorRed = "#dc3545"
  [[params.socialIcons]]
    icon = "fab fa-github"
    title = "GitHub"
    url = "https://github.com/Baitinq"
  [[params.socialIcons]]
    icon = "fas fa-key"
    title = "Keybase"
    url = "https://keybase.io/baitinq"
  [[params.socialIcons]]
    icon = "fab fa-linkedin"
    title = "LinkedIn"
    url = "https://www.linkedin.com/in/manuelpalenzuelamerino"
  [[params.socialIcons]]
    icon = "fas fa-envelope"
    title = "E-mail"
    url = "mailto:manuelpalenzuelamerino@gmail.com"

[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
  [[menu.main]]
    name = "Resume"
    url = "/Manuel_Palenzuela_Merino_Resume.pdf"
    weight = 5
  [[menu.main]]
    name = "Projects"
    url = "/projects"
    weight = 3
  [[menu.main]]
    name = "Blog"
    url = "/blog"
    weight = 4
  [[menu.main]]
    name = "Git"
    url = "https://git.leunam.dev"
    weight = 2

[permalinks]
  blog = "/blog/:filename"
  projects = "/project/:filename"

[markup.goldmark.renderer]
  unsafe = true
